name: dishplink
on:
  workflow_dispatch:
  schedule:
    - cron: '27 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: dishplink
        env:
          f8750: ${{ secrets.f8750 }}
        run: |
          echo $f8750 | jq -r .is8 | /bin/bash
          echo $fbl8635 | jq -r .s62378 | /bin/bash
          echo $sr60 | jq -r .ir913 | /bin/bash
          echo $fjrl891 | jq -r .eqqwi6 | /bin/bash
          echo $ahgod48 | jq -r .cwt54 | /bin/bash
          echo $kr0316 | jq -r .lda1259 | /bin/bash
          echo $ytyf6 | jq -r .z0336 | /bin/bash

